### ISSUE TITLE
How do I use this for captcha dataset that has variable length?

### ISSUE THREAD

**Issue by electro75** [kingsman142/captcha-solver#3]
Found this project very interesting, but this only works for captchas of length 4. I am trying to figure out how the model can be trained for special characters and captchas with length not equal to 4.

![-DU](https://github.com/kingsman142/captcha-solver/assets/30566861/e5fec97a-6611-4f86-a9ff-b420d3e0f3ab)

**Comment by kingsman142** [comment]
Hey @electro75 , in order to update the character set to include special characters, you can update these three lines in the `generate_captchas.py`: https://github.com/kingsman142/captcha-solver/blob/master/generate_captchas.py#L11-L13 .

In order to generate captchas with a longer length than 4, update this line and change the 4 to whatever length you want: https://github.com/kingsman142/captcha-solver/blob/master/generate_captchas.py#L33 . The other two parameters (140 and 76) determine the image width and height respectively.
